'''
Created on Mar 23, 2014

@author: Daniel Corroto

Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?
'''
from math import sqrt

def getPentagonal(x):
    return x * (3 * x - 1) // 2

def isPentagonal(x):
    y = (sqrt(1 + 24 * x) + 1) / 6
    return int(y) * int(y) == y * y

def findPentagonal():
    i = 0
    while True:
        i += 1
        pi = getPentagonal(i)
        for j in xrange(1, i):
            pj = getPentagonal(j)
            if isPentagonal(pi + pj) and isPentagonal(pi - pj):
                return pi - pj

print findPentagonal()
