'''
Created on Mar 19, 2014

@author: Daniel Corroto

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

'''

from numberUtil import getDivisors

def triangleNumberGenerator():
    count = 1
    num = 0
    while True:
        num += count
        yield num
        count += 1

def getTriangleNumberByDivisors(x):
    for i in triangleNumberGenerator():
        if (len(getDivisors(i)) > x):
            return i

print getTriangleNumberByDivisors(500)